### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [Daniel-Tran3/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - please use backticks to format terminal commands as code
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - I can see the method you came up with and it's great! just include the command in your last paragraph as well
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by Daniel-Tran3** [comment]
It says on the regrade guide that we'll see a regrade request button once the assignment is graded, but right now it isn't showing up as graded on Gradescope. Should I wait, or is there another way to submit regrade requests?

**Comment by farnaf** [comment]
Hi there! Yeah since the grades aren't released yet, you can't submit regrade request.
You can either wait until then or let me know here once your website is updated and I can update your grade (:

**Comment by Daniel-Tran3** [comment]
Great! I think it's updated right now.

**Comment by farnaf** [comment]
Sweet, updated your grade!
